server:
  port: 9201
service-url:
  user-service: http://localhost:8201
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      routes:
        - id: requestratelimiter_route
          uri: http://localhost:8201
          filters:
            - name: c
              args:
                redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量（令牌桶每秒填充平均速率）
                redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量(令牌总容量)
                key-resolver: "#{@ipKeyResolver}" #限流策略，对应策略的Bean
          predicates:
              - Method=GET