server:
  port: 8207
spring:
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        namespace: 21407b2a-b001-4802-ac24-b2d81ebbe054
      config:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
